name: ci
on: [pull_request]

# TODO: we clould run other checks as well (e.g. tf linting, docs creation etc.), maybe even via pre-commit
jobs:
  commitlint:
    runs-on: zon-ubuntu-general-dind
    steps:
      - uses: actions/checkout@v3
      - uses: wagoid/commitlint-github-action@v5

  tests:
    runs-on: zon-ubuntu-general-dind
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Call baseproject GHA
      id: baseproject
      uses: ./
      with:
        project_name: github-actions-baseproject-tests
        gke_auth: true
        vault_export_token: true
        gcr_auth: true
        gar_docker_auth: true

    - name: '[TEST] List GKE Clusters in Google Cloud'
      run: gcloud container clusters list

    - name: '[TEST] Create a Kubernetes ConfigMap'
      run: kubectl create configmap test-runner-${{ github.run_id }}-${{ github.run_attempt }} --from-literal=foo=bar

    - name: '[TEST] Read example value from Vault'
      uses: hashicorp/vault-action@v2
      with:
        url: ${{ steps.baseproject.outputs.vault_addr }}
        token: ${{ steps.baseproject.outputs.vault_token }}
        role: ${{ steps.baseproject.outputs.gha_vault_role }}
        secrets: |
          zon/v1/github-actions-baseproject-tests/example foo | EXAMPLE_VAULT_VALUE ;
    