name: ci
on: [pull_request]

# TODO: we clould run other checks as well (e.g. tf linting, docs creation etc.), maybe even via pre-commit
jobs:
  commitlint:
    runs-on: zon-ubuntu-general-dind
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5
      - uses: wagoid/commitlint-github-action@0184f5a228ee06430bb9e67d65f73a1a6767496a # v6

  tests:
    runs-on: zon-ubuntu-general-dind
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

    - name: Call baseproject GHA
      id: baseproject
      uses: ./
      with:
        project_name: github-actions-baseproject-tests
        gke_auth: true
        vault_export_token: true
        gcr_auth: true
        gar_docker_auth: true

    - name: '[TEST] List GKE Clusters in Google Cloud'
      run: gcloud container clusters list

    - name: '[TEST] Create a Kubernetes ConfigMap'
      run: kubectl create configmap test-runner-${{ github.run_id }}-${{ github.run_attempt }} --from-literal=foo=bar

    - name: '[TEST] Read example value from Vault'
      uses: hashicorp/vault-action@d1720f055e0635fd932a1d2a48f87a666a57906c # v3
      with:
        url: ${{ steps.baseproject.outputs.vault_addr }}
        token: ${{ steps.baseproject.outputs.vault_token }}
        role: ${{ steps.baseproject.outputs.gha_vault_role }}
        secrets: |
          zon/v1/github-actions-baseproject-tests/example foo | EXAMPLE_VAULT_VALUE ;

    - name: '[TEST] Run docker build'
      run: |
        docker buildx build --output type=docker \
          --cache-from type=gha --cache-to type=gha,mode=max \
          --tag test ./test
