on:
  push:
    tags:
      - 'v*'
      - '!v0'

name: Create Release

jobs:
  test:
    name: Run tests
    runs-on: self-hosted

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Baseproject
        uses: ZeitOnline/gh-action-baseproject@$GITHUB_REF
        with:
          project_name: github-actions-baseproject-tests
          environment: production
          gke_auth: true
          gar_docker_auth: true
      - run: false # always fail

  build:
    name: Create Release
    runs-on: ubuntu-latest # run on hosted runner, because it's a public repo
    needs: test
    permissions:
      contents: write

    env:
      rolling_tag: v0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Retrieve annotated tags
        run: |
          git fetch --tags --force

      - name: Get tag annotation
        uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Release ${{ github.ref }}
          body: |
            ${{ steps.tag-data.outputs.git-tag-annotation }}
          draft: false
          prerelease: false

      - name: Move rolling tag
        run: |
          git tag -d ${{ env.rolling_tag }} && git push --delete origin ${{ env.rolling_tag }}
          git tag ${{ env.rolling_tag }} && git push origin ${{ env.rolling_tag }}
