on:
  push:
    branches:
      - main
    paths:
      - 'action.yml'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest # run on hosted runner, because it's a public repo
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: gh-action-baseproject
