on:
  push:
    branches:
      - main

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest # run on hosted runner, because it's a public repo
    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

      - uses: actions/checkout@v4

      - name: tag major and minor versions
        uses: zeitonline/gh-action-workflows-ops/.github/workflows/tag-rolling-release.yaml@main
        if: ${{ steps.release.outputs.release_created }}
        with:
          runs-on: zon-ubuntu-general-dind
          major: ${{ steps.release.outputs.major }}
          minor: ${{ steps.release.outputs.minor }}
