on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'renovate.json'

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest # run on hosted runner, because it's a public repo
    permissions:
      contents: write
      pull-requests: write

    steps:
      - id: release
        uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple

    outputs:
      major: ${{ steps.release.outputs.major }}
      minor: ${{ steps.release.outputs.minor }}
      release_created: ${{ steps.release.outputs.release_created }}

  tag:
    name: Tag Major and Minor Versions
    uses: zeitonline/gh-action-workflows-ops/.github/workflows/tag-rolling-release.yaml@main

    needs: release
    if: ${{ needs.release.outputs.release_created }}

    with:
      runs-on: ubuntu-latest # run on hosted runner, because it's a public repo
      major: ${{ needs.release.outputs.major }}
      minor: ${{ needs.release.outputs.minor }}
