name: Self-Surveillance Check
on: [pull_request]

# TODO: we clould run other checks as well (e.g. tf linting, docs creation etc.), maybe even via pre-commit
jobs:
  tests:
    runs-on: zon-ubuntu-general-dind
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Zizmor check
      id: zizmor
      uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2
      with: 
        advanced-security: false
        min-severity: medium
        inputs: |
          .github/workflows/
          action.yml

    - name: Call baseproject GHA
      id: baseproject
      uses: ./
      with:
        project_name: github-actions-baseproject-tests
        gke_auth: false
        vault_export_token: true
        gar_docker_auth: true
        alerting_channel: C04US01KGN7 # test-slackbot
