name: Test

on: workflow_dispatch

jobs:
  test:
    name: Test
    runs-on: [self-hosted,linux]
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run Tests
      id: run
      uses: ./
      with:
        project_name: github-actions-baseproject-tests
  
  release:
    name: Release
    needs: test
    runs-on: [self-hosted,linux]
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: gh-action-baseproject
