name: Tests

on: pull_request

jobs:
  test:
    name: Run Tests
    runs-on: [self-hosted,linux]
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Run Tests
      id: run
      uses: ./
      with:
        project_name: github-actions-baseproject-tests

